//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using OpenAuth.Repository.Core;

namespace OpenAuth.Repository.Domain
{
    /// <summary>
	/// 工作流实例操作记录
	/// </summary>
      [Table("fl_flowinstanceoperationhistory")]
    public partial class FlowInstanceOperationHistory : Entity
    {
        public FlowInstanceOperationHistory()
        {
            this.InstanceId = string.Empty;
            this.Content = string.Empty;
            this.CreateDate = DateTime.Now;
            this.CreateUserId = string.Empty;
            this.CreateUserName = string.Empty;
            this.NodeId = string.Empty;
            this.NodeName = string.Empty;
            this.NextNodeId = string.Empty;
            this.NextNodeName = string.Empty;
            this.Opinion = string.Empty;
            this.Result = string.Empty;
            this.CreateUserJob = string.Empty;
            //this.BeginTime = DateTime.Now;
            //this.EndTime = DateTime.Now;
            this.OperateList = string.Empty;
        }

        /// <summary>
	    /// 实例进程Id
	    /// </summary>
         [Description("实例进程Id")]
        public string InstanceId { get; set; }
        /// <summary>
	    /// 操作内容
	    /// </summary>
         [Description("操作内容")]
        public string Content { get; set; }
        /// <summary>
	    /// 创建时间
	    /// </summary>
         [Description("创建时间")]
        public System.DateTime CreateDate { get; set; }
        /// <summary>
	    /// 创建用户主键
	    /// </summary>
         [Description("创建用户主键")]
        public string CreateUserId { get; set; }
        /// <summary>
	    /// 创建用户
	    /// </summary>
         [Description("创建用户")]
        public string CreateUserName { get; set; }

        /// <summary>
        /// 节点id
        /// </summary>
        [Description("节点id")]
        public string NodeId { get; set; }

        /// <summary>
        /// 节点名称
        /// </summary>
        [Description("节点名称")]
        public string NodeName { get; set; }

        /// <summary>
        /// 节点开始时间
        /// </summary>
        [Description("节点开始时间")]
        public System.DateTime BeginTime { get; set; }

        /// <summary>
        /// 节点结束时间
        /// </summary>
        [Description("节点结束时间")]
        public System.DateTime EndTime { get; set; }

        /// <summary>
        /// 审批意见
        /// </summary>
        [Description("审批意见")]
        public string Opinion { get; set; }

        /// <summary>
        /// 审批人岗位
        /// </summary>
        [Description("审批人岗位")]
        public string CreateUserJob { get; set; }

        /// <summary>
        /// 审批结果
        /// </summary>
        [Description("审批结果")]
        public string Result { get; set; }

        /// <summary>
        /// 允许操作人（角色、部门、人）
        /// </summary>
        [Description("允许操作人（角色、部门、人）")]
        public string OperateList { get; set; }

        /// <summary>
        /// 下一节点id
        /// </summary>
        [Description("下一节点id")]
        public string NextNodeId { get; set; }

        /// <summary>
        /// 下一节点名称
        /// </summary>
        [Description("下一节点名称")]
        public string NextNodeName { get; set; }
    }
}