//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using OpenAuth.Repository.Core;

namespace OpenAuth.Repository.Domain
{
    /// <summary>
	/// 工作流流程实例表
	/// </summary>
      [Table("fl_flowinstance")]
    public partial class FlowInstance : Entity
    {
        public FlowInstance()
        {
            this.InstanceSchemeId = "";
            this.Code = "";
            this.CustomName = "";
            this.ActivityId = "";
            this.ActivityName = "";
            this.PreviousId = "";
            this.SchemeContent = "";
            this.SchemeId = "";
            this.DbName = "";
            this.FrmData = "";
            this.FrmType = 0;
            this.FrmContentData = "";
            this.FrmContentParse = "";
            this.FrmId = "";
            this.SchemeType = "";
            this.Disabled = 0;
            this.CreateDate = DateTime.Now;
            this.CreateUserId = "";
            this.CreateUserName = "";
            this.FlowLevel = 0;
            this.Description = "";
            this.IsFinish = 0;
            this.MakerList = "";
            this.UninId = "";
            this.CreateCompanyId = "";
            this.CreateDeptId = "";
        }

        /// <summary>
	    /// 流程实例模板Id【已废弃】
	    /// </summary>
         [Description("流程实例模板Id")]
        public string InstanceSchemeId { get; set; }
        /// <summary>
	    /// 实例编号
	    /// </summary>
         [Description("实例编号")]
        public string Code { get; set; }
        /// <summary>
	    /// 自定义名称
	    /// </summary>
         [Description("自定义名称")]
        public string CustomName { get; set; }
        /// <summary>
	    /// 当前节点ID
	    /// </summary>
         [Description("当前节点ID")]
        public string ActivityId { get; set; }
        /// <summary>
	    /// 当前节点类型（0会签节点）
	    /// </summary>
         [Description("当前节点类型（0会签节点）")]
        public int? ActivityType { get; set; }
        /// <summary>
	    /// 当前节点名称
	    /// </summary>
         [Description("当前节点名称")]
        public string ActivityName { get; set; }
        /// <summary>
	    /// 前一个ID
	    /// </summary>
         [Description("前一个ID")]
        public string PreviousId { get; set; }
        /// <summary>
	    /// 流程模板内容
	    /// </summary>
         [Description("流程模板内容")]
        public string SchemeContent { get; set; }
        /// <summary>
	    /// 流程模板ID
	    /// </summary>
         [Description("流程模板ID")]
        public string SchemeId { get; set; }
        /// <summary>
	    /// 数据库名称
	    /// </summary>
         [Description("数据库名称")]
        public string DbName { get; set; }
        /// <summary>
	    /// 表单数据
	    /// </summary>
         [Description("表单数据")]
        public string FrmData { get; set; }
        /// <summary>
	    /// 表单类型
	    /// </summary>
         [Description("表单类型")]
        public int FrmType { get; set; }
        /// <summary>
	    /// 表单中的控件属性描述
	    /// </summary>
         [Description("表单中的控件属性描述")]
        public string FrmContentData { get; set; }
        /// <summary>
	    /// 表单控件位置模板
	    /// </summary>
         [Description("表单控件位置模板")]
        public string FrmContentParse { get; set; }
        /// <summary>
	    /// 表单ID
	    /// </summary>
         [Description("表单ID")]
        public string FrmId { get; set; }
        /// <summary>
	    /// 流程类型
	    /// </summary>
         [Description("流程类型")]
        public string SchemeType { get; set; }
        /// <summary>
	    /// 有效标志
	    /// </summary>
         [Description("有效标志")]
        public int Disabled { get; set; }
        /// <summary>
	    /// 创建时间
	    /// </summary>
         [Description("创建时间")]
        public System.DateTime CreateDate { get; set; }
        /// <summary>
	    /// 创建用户主键
	    /// </summary>
         [Description("创建用户主键")]
        public string CreateUserId { get; set; }
        /// <summary>
	    /// 创建用户
	    /// </summary>
         [Description("创建用户")]
        public string CreateUserName { get; set; }
        /// <summary>
	    /// 等级
	    /// </summary>
         [Description("等级")]
        public int FlowLevel { get; set; }
        /// <summary>
	    /// 实例备注
	    /// </summary>
         [Description("实例备注")]
        public string Description { get; set; }
        /// <summary>
        /// 是否完成（是否完成(0正常，1完结，2不同意（终止），4驳回起始，5退回编辑）
        /// </summary>
        [Description("是否完成")]
        public int IsFinish { get; set; }
        /// <summary>
	    /// 执行人
	    /// </summary>
         [Description("执行人")]
        public string MakerList { get; set; }

        /// <summary>
        /// 外链id
        /// </summary>
        [Description("外链id")]
        public string UninId { get; set; }

        /// <summary>
        /// 所属公司Id
        /// </summary>
        [Description("所属公司Id")]
        public string CreateCompanyId { get; set; }

        /// <summary>
        /// 发起部门id
        /// </summary>
        [Description("发起部门id")]
        public string CreateDeptId { get; set; }
    }
}