//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using OpenAuth.Repository.Core;

namespace OpenAuth.Repository.Domain
{
    /// <summary>
	/// 工作流流程实例流转记录表表
	/// </summary>
      [Table("fl_flowinstancelog")]
    public partial class FlowInstanceLog : Entity
    {
        /// <summary>
	    /// 流程实例Id
	    /// </summary>
         [Description("流程实例Id")]
        public string FlowinstanceId { get; set; }
        /// <summary>
        /// 外关联id
        /// </summary>
        [Description("外关联id")]
        public string UninId { get; set; }
        /// <summary>
	    /// 当前节点ID
	    /// </summary>
         [Description("当前节点ID")]
        public string ActivityId { get; set; }
        /// <summary>
	    /// 当前节点类型（0会签节点）
	    /// </summary>
         [Description("当前节点类型（0会签节点）")]
        public int? ActivityType { get; set; }
        /// <summary>
	    /// 当前节点名称
	    /// </summary>
         [Description("当前节点名称")]
        public string ActivityName { get; set; }
        /// <summary>
	    /// 前一个ID
	    /// </summary>
         [Description("前一个ID")]
        public string PreviousId { get; set; }
        /// <summary>
	    /// 创建时间
	    /// </summary>
         [Description("创建时间")]
        public System.DateTime CreateDate { get; set; }
        /// <summary>
	    /// 创建用户主键
	    /// </summary>
         [Description("创建用户主键")]
        public string CreateUserId { get; set; }
        /// <summary>
	    /// 创建用户
	    /// </summary>
         [Description("创建用户")]
        public string CreateUserName { get; set; }
        /// <summary>
	    /// 执行人
	    /// </summary>
         [Description("执行人")]
        public string MakerList { get; set; }
        /// <summary>
        /// 执行人姓名
        /// </summary>
        [Description("执行人")]
        public string MakerNameList { get; set; }
        
        /// <summary>
        /// 所属公司Id
        /// </summary>
        [Description("所属公司Id")]
        public string CreateCompanyId { get; set; }
        /// <summary>
        /// 所属公司名称
        /// </summary>
        [Description("所属公司名称")]
        public string CreateCompanyName { get; set; }
        /// <summary>
        /// 发起部门id
        /// </summary>
        [Description("发起部门id")]
        public string CreateDeptId { get; set; }
        /// <summary>
        /// 发起部门id
        /// </summary>
        [Description("发起部门名称")]
        public string CreateDeptName { get; set; }
    }
}